version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
build:
  publish_wap: true
  verbosity: minimal
test: off
after_deploy:
- ps: "Function Set-ConnectionString{\n	[CmdletBinding(SupportsShouldProcess=$True)]\n	Param(\n        [string]$fileName=\"app.config\",\n        [string]$connectionStringName,\n        [string]$connectionString\n    )\n	\n	$config = [xml](Get-Content -LiteralPath $fileName)\n	\n    $config.Configuration.connectionStrings\n    \n	$connStringElement = $config.SelectSingleNode(\"configuration/connectionStrings/add[@name='$connectionStringName']\")\n    \n    if($connStringElement) {\n        \n        $connStringElement.connectionString = $connectionString\n    	\n    	if($pscmdlet.ShouldProcess(\"$fileName\",\"Modify app.config connection string\")){\n    		Write-Host (\"Updating app.config connection string {0} to be {1}\" -f $connectionStringName, $connectionString)\n    	\n    		$config.Save($fileName)\n    	}\n    }\n    else{\n        Write-Error \"Unable to locate connection string named: $connectionStringName\"\n    }\n}\n\nSet-ConnectionString \"C:\\appveyor\\projects\\its-irrelevant-really\\applications\\ScavengerHunt\\web.config\" DefaultConnection \"Data Source=.\\SCAVENGERHUNT;Initial Catalog=SCAVENGERHUNT;Integrated Security=True\""